In [1]:
import numpy as np
import random
import math

In [2]:
wvl = np.arange(1500, 1800, 1)

In [3]:
wvl

array([1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510,
       1511, 1512, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521,
       1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532,
       1533, 1534, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543,
       1544, 1545, 1546, 1547, 1548, 1549, 1550, 1551, 1552, 1553, 1554,
       1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565,
       1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1576,
       1577, 1578, 1579, 1580, 1581, 1582, 1583, 1584, 1585, 1586, 1587,
       1588, 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598,
       1599, 1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609,
       1610, 1611, 1612, 1613, 1614, 1615, 1616, 1617, 1618, 1619, 1620,
       1621, 1622, 1623, 1624, 1625, 1626, 1627, 1628, 1629, 1630, 1631,
       1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642,
       1643, 1644, 1645, 1646, 1647, 1648, 1649, 16

In [4]:
range_widths = [10, 20, 30, 40, 50]
n_ranges = [1, 2, 3, 4, 5]
n_solutions = 10

In [6]:
ranges = random.choice(n_ranges)

In [8]:
random.randint(10, 20)

14

In [19]:
def random_pop(wvl):
    chromossomes = np.array([[0]*max(n_ranges)*2]*n_solutions)
    for solution in range(n_solutions):
        ranges = random.choice(n_ranges)
        chromossomes[solution] = np.array([0]*max(n_ranges)*2)
        
        array_slice = math.floor(len(wvl)/ranges)
        
        for rng in range(ranges):
            slc = wvl[rng*array_slice:array_slice*(rng+1)]
            if rng == ranges-1:
                slc = wvl[rng*array_slice:]
            
            range_width = random.choice(range_widths)
            initial_wv = random.randint(slc[0], slc[-range_width+1])            
            chromossomes[solution][rng*2] = initial_wv
            chromossomes[solution][rng*2+1] = range_width

    return chromossomes

In [20]:
random_pop(wvl)

array([[1547,   40, 1620,   30, 1747,   20,    0,    0,    0,    0],
       [1507,   50, 1638,   50, 1755,   30,    0,    0,    0,    0],
       [1525,   20, 1627,   50, 1727,   20,    0,    0,    0,    0],
       [1509,   10, 1563,   30, 1647,   30, 1694,   10, 1783,   10],
       [1527,   30, 1569,   50, 1626,   40, 1685,   30, 1744,   50],
       [1546,   50, 1627,   40, 1736,   50,    0,    0,    0,    0],
       [1521,   30, 1601,   50, 1704,   10,    0,    0,    0,    0],
       [1534,   20, 1602,   10, 1655,   30, 1751,   10,    0,    0],
       [1521,   40, 1593,   50, 1670,   40, 1745,   50,    0,    0],
       [1533,   20, 1570,   50, 1632,   20, 1695,   10, 1746,   50]])

In [21]:
c =  [1533,   20, 1570,   50, 1632,   20, 1695,   10, 1746,   50];

In [63]:
random.randint(0, 1)

0

In [115]:
def mutation(chromossome):
    #     array com 0 nas últimas posições?
        new_chromossome = np.array([0]*10)
        for value, ctr in zip(chromossome, range(10)):
            while(True):
                new_num = []
                for i in str(value):
                    prob = random.randint(1,100)
                    if (ctr+1)%2 != 0 and ctr == 0:
                        value_to_append = random.randint(0,1) if prob <= 0.1*100 else int(i)
                        new_num.append(value_to_append)
                    else:
                        value_to_append = random.randint(0,9) if prob <= 0.1*100 else int(i)
                        new_num.append(value_to_append)
                
                int_new_num = int(''.join(str(i) for i in new_num))
                if ((ctr+1)%2 != 0 and int_new_num < 1799):
                    new_chromossome[ctr] = int_new_num
                    break
                elif ((ctr+1)%2 == 0 and int_new_num+new_chromossome[ctr-1] < 1799):
                    new_chromossome[ctr] = int_new_num
                    break
        
        return new_chromossome

In [138]:
mutation(c)

array([1533,   20, 1570,   50, 1632,   20, 1695,   10, 1746,   50])