In [65]:
import numpy as np
import random
import math

In [2]:
wvl = np.arange(1500, 1800, 1)

In [4]:
wvl

array([1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510,
       1511, 1512, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521,
       1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532,
       1533, 1534, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543,
       1544, 1545, 1546, 1547, 1548, 1549, 1550, 1551, 1552, 1553, 1554,
       1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565,
       1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1576,
       1577, 1578, 1579, 1580, 1581, 1582, 1583, 1584, 1585, 1586, 1587,
       1588, 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598,
       1599, 1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609,
       1610, 1611, 1612, 1613, 1614, 1615, 1616, 1617, 1618, 1619, 1620,
       1621, 1622, 1623, 1624, 1625, 1626, 1627, 1628, 1629, 1630, 1631,
       1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642,
       1643, 1644, 1645, 1646, 1647, 1648, 1649, 16

In [95]:
range_widths = [10, 20, 30, 40, 50]
n_ranges = [1, 2, 3, 4, 5]
n_solutions = 10

In [85]:
wvl[(rng-1)*array_slice:array_slice*rng]

array([1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709, 1710,
       1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721,
       1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732,
       1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743,
       1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754,
       1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763, 1764, 1765,
       1766, 1767, 1768, 1769, 1770, 1771, 1772, 1773, 1774, 1775, 1776,
       1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787,
       1788, 1789, 1790, 1791, 1792, 1793, 1794, 1795, 1796, 1797, 1798,
       1799])

In [88]:
ranges = random.choice(n_ranges)

In [92]:
for a in range(5):
    print(a)

0
1
2
3
4


In [101]:
random.randint(10, 20)

16

In [219]:
def random_pop(wvl):
    chromossomes = np.array([[0]*max(n_ranges)*2]*n_solutions)
    for solution in range(n_solutions):
        ranges = random.choice(n_ranges)
        chromossomes[solution] = np.array([0]*max(n_ranges)*2)
        
        array_slice = math.floor(len(wvl)/ranges)
        
        for rng in range(ranges):
            slc = wvl[rng*array_slice:array_slice*(rng+1)]
            if rng == ranges-1:
                slc = wvl[rng*array_slice:]
            
            range_width = random.choice(range_widths)
            initial_wv = random.randint(slc[0], slc[-range_width+1])            
            chromossomes[solution][rng*2] = initial_wv
            chromossomes[solution][rng*2+1] = range_width

    return chromossomes

In [220]:
random_pop(wvl)

number of ranges: 3
slice_max_size: 100
random range width: 50
first wv: 1524
random range width: 10
first wv: 1648
random range width: 40
first wv: 1753
number of ranges: 2
slice_max_size: 150
random range width: 30
first wv: 1597
random range width: 10
first wv: 1784
number of ranges: 4
slice_max_size: 75
random range width: 20
first wv: 1549
random range width: 30
first wv: 1603
random range width: 20
first wv: 1650
random range width: 40
first wv: 1761
number of ranges: 3
slice_max_size: 100
random range width: 20
first wv: 1520
random range width: 30
first wv: 1618
random range width: 10
first wv: 1708
number of ranges: 5
slice_max_size: 60
random range width: 50
first wv: 1506
random range width: 10
first wv: 1589
random range width: 20
first wv: 1623
random range width: 30
first wv: 1700
random range width: 10
first wv: 1743
number of ranges: 4
slice_max_size: 75
random range width: 50
first wv: 1526
random range width: 20
first wv: 1582
random range width: 30
first wv: 1679
ran

array([[1524,   50, 1648,   10, 1753,   40,    0,    0,    0,    0],
       [1597,   30, 1784,   10,    0,    0,    0,    0,    0,    0],
       [1549,   20, 1603,   30, 1650,   20, 1761,   40,    0,    0],
       [1520,   20, 1618,   30, 1708,   10,    0,    0,    0,    0],
       [1506,   50, 1589,   10, 1623,   20, 1700,   30, 1743,   10],
       [1526,   50, 1582,   20, 1679,   30, 1744,   30,    0,    0],
       [1548,   50, 1655,   30, 1730,   10,    0,    0,    0,    0],
       [1580,   40, 1708,   40,    0,    0,    0,    0,    0,    0],
       [1515,   40, 1580,   40, 1650,   30, 1700,   30, 1743,   50],
       [1607,   40,    0,    0,    0,    0,    0,    0,    0,    0]])